apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicast
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend
    
# kubectl run 
# kubectl scale --replica=3 replicasetname