apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: nginx
    tier: frontend


# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: 80
#   selector:
#     app: nginx
#     tier: frontend


# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 80
#       nodePort: 30008
#   selector:
#     app: nginx
#     tier: frontend

# minikube service myapp-service --url