apiVersion: v1
kind: Service
metadata:
  name: mongo-container
  labels:
    name: mongo-service
    app: idress-backend-app
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-pod
    app: idress-backend-app