apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    name: mongo-pod
    app: idress-backend-app
spec:
  containers:
    - name: mongo-container
      image: mongo:5.0
      ports:
        - containerPort: 27017
      resources:
        limits:
          memory: 512Mi
          cpu: 1