apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    name: mongo-deploy
    app: idress-backend-app
spec:
  selector:
    matchLabels:
      name: mongo-pod
      app: idress-backend-app
  template:
    containers:
    - name: mongo-container
      image: mongo:5.0
      ports:
        - containerPort: 27017